
const TITLE_MIN_LENGTH = 10;
const TITLE_MAX_LENGTH = 100;
const DESCRIPTION_MIN_LENGTH = 20;
const DESCRIPTION_MAX_LENGTH = 1024;
const ROOMS_MIN = 1;
const ROOMS_MAX = 8;
const GUESTS_MIN = 1;
const GUESTS_MAX = 10;
const COST_MIN = 100;
const COST_MAX = 100000;
const PREVIEW_IMAGE_MAX_LENGTH = 256;
const PHOTOS_MAX_LENGTH = 256;
const PHOTOS_ARRAY_SIZE = 6;

export {TITLE_MIN_LENGTH, TITLE_MAX_LENGTH, DESCRIPTION_MIN_LENGTH, DESCRIPTION_MAX_LENGTH, ROOMS_MIN, ROOMS_MAX, GUESTS_MIN, GUESTS_MAX, COST_MIN, COST_MAX, PREVIEW_IMAGE_MAX_LENGTH, PHOTOS_MAX_LENGTH, PHOTOS_ARRAY_SIZE};

